<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_miniCartLink</name>
   <tag></tag>
   <elementGuidId>c7842b16-4380-40fb-8652-112867fa4511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.desk.cart-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>a.desk.cart-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
